mod div;
mod divu;
mod divuw;
mod divw;
mod mul;
mod mulh;
mod mulhsu;
mod mulhu;
mod mulw;
mod rem;
mod remu;
mod remuw;
mod remw;

pub use div::div;
pub use divu::divu;
pub use divuw::divuw;
pub use divw::divw;
pub use mul::mul;
pub use mulh::mulh;
pub use mulhsu::mulhsu;
pub use mulhu::mulhu;
pub use mulw::mulw;
pub use rem::rem;
pub use remu::remu;
pub use remuw::remuw;
pub use remw::remw;
