name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/webapp

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm ci

    - name: Setup nightly toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
    
    - uses: jetli/trunk-action@v0.5.0
      with:
        version: 'latest'
    
    - name: Run tests
      run: cargo test --all --verbose

    - name: Compile TypeScript bridge
      run: npm run build:ts:release

    - name: Compile Rust codebase
      run: npm run build:rs:public

    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'apps/webapp/dist/final'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    
